### PR TITLE
Intergrate ziontee113/CopilotAgent.nvim

### PR DESCRIPTION
**Pull request by ziontee113**
## WHAT

This PR integrates all libraries from https://github.com/ziontee113/CopilotAgent.nvim
I basically dumped every I've written into this PR.
This PR will not interfere with the current `CopilotChat.nvim`.
This is a starting step to fully integrate the 2 repos together.

## WHY

As discussed in #22 

## HOW

This PR add `copilot-agent.py` (to be renamed later) and all CopilotAgent.nvim's libraries, which after running `UpdateReomotePlugins` in Neovim, acts like its own plugin. So it doesn't have to directly clash with the current `CopilotChat.nvim` when we try to work on how to fully integrate the plugins together.

## Screenshots (if appropriate):

Chat layout to replace code in-place with diff mode.
Screenshot from 2024-01-27 09-23-59

Token count (using `tiktoken`), Folded system prompt, Folded code prompt
Screenshot from 2024-01-27 09-24-31

Unfolded
Screenshot from 2024-01-27 09-24-47

Example of `Layout` library
Screenshot from 2024-01-27 09-23-24

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] Linter
- [ ] Tests
- [ ] Review comments
- [ ] Security

### CODE REVIEW

**Comment by jellydn** [comment]
Hi @ziontee113 That's great work. Could you add a section on readme for how to use the new command? I am thinking about the case when we are merging this to `main` branch, which would be super useful for the end user. Thanks. Or if you don't do it now, let's merge and do it on next PR.

@gptlang any comments on this PR?

**Comment by ziontee113** [comment]
@jellydn I think we should merge this one first if you don't see any problems with it. The docs can come in a later PR. 

My question is how do you feel about replacing the old API to use this new one?

**Comment by jellydn** [comment]
> docs can come in a later PR

Yeah, it works. No problem at all.

> My question is how do you feel about replacing the old API to use this new one?

Let's write RFC if you don't mind https://dev.to/wasp/develop-the-right-thing-every-time-and-become-a-10x-engineer-the-art-of-writing-rfcs-2mc6

**Comment by ziontee113** [comment]
Thank you for sharing. I'll look into it.

**Comment by ziontee113** [comment]
@jellydn @gptlang I wonder about your direction for the project language wise.

I personally prefer Python over Lua. What do you guys think?

**Comment by ziontee113** [comment]
@jellydn this is my draft for the RFC. I now realized I'm kinda screwed up by porting everything from CopilotAgent in a single PR. This should've been multiple RFCs / PRs.

# RFC: Replacing current CopilotChat command implementation with CopilotAgent implemetation

## Summary

This RFC proposes the replacement of the current `CopilotChat` command implementation. This will allow for a clearer and more robust module system that can be easily extended in the future.

## Motivation

The current `copilot-plugin.py` file is currently having too many responsibilities. From authenticating to interacting with Copilot to rendering the response. This makes the code difficult to comprehend and difficult to maintain as we keep adding more features.

## Solution & Implementation

We can solve this problem by separating the responsibilities into smaller modules.

For example:

- The `handlers/chat_handler.py` module only has the responsibility to call the Copilot class and display the response into the chat buffer.
- The `handlers/vsplit_chat_handler` only has the responsibility to manage the vsplit window.

**Comment by gptlang** [comment]
> direction for the project language wise.

I primarily write Python but thought that Lua might be more suitable for a Neovim plugin considering that's what most plugins are written in. However, given you're obviously more experienced with writing plugins, I'd take your word for it. Keeping it in Python would definitely make life much easier.

**Comment by ziontee113** [comment]
# RFC: Adding custom wrappers around `pynvim` API

## Summary

This RFC proposes the adding custom wrappers around `pynvim` API and use them in the codebase moving forward. This allows for more convenient API calls to Neovim when working with the Neovim instance, Buffers and Windows.
## Motivation

The current `pynvim` API is good, however we can write our own wrappers to add more convenient features to it.

## Solution & Implementation

For example:

- Add methods like `self.nvim.notify("Hello World")`, or `self.nvim.feed(keys_to_feed)`
- Having a custom Buffer class that can have methods like `buffer.map("n", "q", ":q<CR>")`

The code for this proposal can be found in `mypynvim/` module

**Comment by ziontee113** [comment]
> Keeping it in Python would definitely make life much easier.
@gptlang If you also think so that it's wonderful. I just get burned out very quickly when working with Lua for some reason. I've been writing Lua for 2 years and the experience writing it just deteriorate overtime. I don't know why.

**Comment by gptlang** [comment]
Re: pynvim wrappers

I previously got stuck on tree sitter as it wasn't exposed by pynvim. Any idea how we could bind that for use in Python? (for the embeddings)

**Comment by ziontee113** [comment]
# RFC: Adding UI components like nui.nvim

## Summary

This RFC proposes adding UI components like `nui.nvim`. Allows for quick popup / layout creating using Python.

## Motivation

Creating a PopUp or a Layout of multiple PopUps should be easy. `Nui.nvim` has wonderful a API system so I'm trying to mimic it.

## Solution & Implementation

Solution can be found in `mypynvim/ui_components/`.
Examples can be found at `tools/priority_matrix.py` and `handlers/inplace_chat_handler.py`

**Comment by ziontee113** [comment]
> I previously got stuck on tree sitter as it wasn't exposed by pynvim. Any idea how we could bind that for use in Python? (for the embeddings)

@gptlang We could write all the Treesitter API related functions in Lua, and then call them in Python.

**Comment by jellydn** [comment]
> I personally prefer Python over Lua. What do you guys think?

@ziontee113 @gptlang While I'm inclined towards Python, I see the value in Lua, especially for Neovim plugins. How about we combine both? For example, using Lua in spinner.lua with Python support has worked well. 

```python
# Start the spinner
        self.nvim.exec_lua('require("CopilotChat.spinner").show()')
```

Considering the issues with Python ([Issue #18](https://github.com/gptlang/CopilotChat.nvim/issues/18), [Issue #16](https://github.com/gptlang/CopilotChat.nvim/issues/16)), a hybrid approach could be our best bet for wider community involvement.

By the way, re. the RFC for UI components
> RFC: Adding UI components like nui.nvim

I think our focus should primarily be on enhancing the 'GitHub Copilot Chat' features and leveraging community plugins where possible. However, if our implementation is working well,  I'm open to it.

**Comment by ziontee113** [comment]
@jellydn About making UI components: I made them because I think having a Layout API will be very necessary for the present and future. Also I love nui.nvim but I'm really burned out from Lua. I don't want to write Lua unless absolutely necessary. 

It's a shame that people are having trouble with pynvim. I can't really help with that.

**Comment by jellydn** [comment]
Thanks @ziontee113 Could you open a new PR for `CopilotAgent` documentation?

**Comment by ziontee113** [comment]
Yeah I'll do so. Just add it to the readme?

**Comment by jellydn** [comment]
> Just add it to the readme?
Yes, let's do it.

**Pull request merged**
